name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: ytang/os
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: make
      run: make
    
    - name: test
      run: ./nyuc Hello, world
